const FETCH_DATA = 'FETCH_DATA';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

const ADD_TODO_LIST = 'ADD_TODO_LIST';
const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

const URL_TODO_LIST = 'https://6099ee090f5a130017219c8c.mockapi.io/api/todoapp/foods/'

export { 
  FETCH_DATA,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAIL,
  ADD_TODO_LIST,
  ADD_TODO_FAILED,
  URL_TODO_LIST
}
